import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getAuthenticatedAppForUser } from "@/src/lib/firebase/serverApp";
import Header from "@/src/components/Header";
import "./globals.css";
import pokemon from "pokemontcgsdk";

pokemon.configure({ apiKey: process.env.POKEMON_API_KEY });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { currentUser } = await getAuthenticatedAppForUser();
  return (
    <html lang="en">
      <head>
        <title>Next.js</title>
      </head>
      <body>
        <div className="flex">
        <div className="sidebar w-64 h-screen bg-gray-800 text-white">
            <nav className="flex flex-row">
              <ul>
                <li className="mb-4">
                  <div>TCG Stocks</div>
                </li>
                <li className="mb-2">
                  <a href="/">Home</a>
                </li>
                <li className="mb-2">
                  <a href="/sets">TCG Sets</a>
                </li>
                <li className="mb-2">
                  <a href="/news">News</a>
                </li>
              </ul>
            </nav>
        </div>
        <div>
        <Header initialUser={currentUser?.toJSON()}/>
        </div>
        <div className="container mx-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
