import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getAuthenticatedAppForUser } from "@/src/lib/firebase/serverApp";
import Header from "@/src/app/components/Header";
import "./globals.css";
import pokemon from "pokemontcgsdk";
import SearchBar from "./components/SearchBar";
import { UserProvider } from "@/src/app/Context/userContext";

pokemon.configure({ apiKey: process.env.POKEMON_API_KEY });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { currentUser } = await getAuthenticatedAppForUser();
  return (
    <html lang="en">
      <head>
        <title>Next.js</title>
      </head>
      <body>
        <UserProvider>
          <div className="m-auto max-w-screen-2xl">
            <div className="">
              <div className="inset-x-0 top-0 bg-gray-800 z-10">
                <Header />
              </div>
              <div className="mt-4 p-4">
                <div className="container mx-auto">{children}</div>
              </div>
            </div>
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
